"""add scene_excerpt translations

Revision ID: 6e9392390ef9
Revises: f3dec31ba972
Create Date: 2026-05-26 21:43:32.630846

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e9392390ef9"
down_revision: str | Sequence[str] | None = "f3dec31ba972"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("illustration_concept_translations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scene_excerpt_localized", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("scene_excerpt_localized_source_hash", sa.String(), nullable=True)
        )
        batch_op.alter_column("concept_localized", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "concept_localized_source_hash", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("illustration_concept_translations", schema=None) as batch_op:
        batch_op.alter_column(
            "concept_localized_source_hash", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("concept_localized", existing_type=sa.TEXT(), nullable=False)
        batch_op.drop_column("scene_excerpt_localized_source_hash")
        batch_op.drop_column("scene_excerpt_localized")

    # ### end Alembic commands ###
