"""add revision_summary_json to illustration_attempt_history

Revision ID: 7d0bc17f54f8
Revises: 8ed262ed0c65
Create Date: 2026-05-30 21:41:11.086968

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0bc17f54f8'
down_revision: str | Sequence[str] | None = '8ed262ed0c65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illustration_attempt_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision_summary_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illustration_attempt_history', schema=None) as batch_op:
        batch_op.drop_column('revision_summary_json')

    # ### end Alembic commands ###
