"""add manual chat fallback tables

Revision ID: e0d7c8c320d3
Revises: 6e9392390ef9
Create Date: 2026-05-27 15:36:29.575203

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0d7c8c320d3"
down_revision: str | Sequence[str] | None = "6e9392390ef9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manual_illustration_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("illustration_id", sa.String(), nullable=False),
        sa.Column("last_manual_image_path", sa.String(), nullable=True),
        sa.Column("last_concept_candidate", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["illustration_id"],
            ["illustrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("illustration_id"),
    )
    op.create_table(
        "manual_messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("illustration_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("manual_attempt_index", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["illustration_id"],
            ["illustrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("manual_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_manual_messages_illustration_id"),
            ["illustration_id"],
            unique=False,
        )

    with op.batch_alter_table("illustrations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("manual_attempts", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("manual_state_json", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("illustrations", schema=None) as batch_op:
        batch_op.drop_column("manual_state_json")
        batch_op.drop_column("manual_attempts")

    with op.batch_alter_table("manual_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_manual_messages_illustration_id"))

    op.drop_table("manual_messages")
    op.drop_table("manual_illustration_sessions")
    # ### end Alembic commands ###
