"""add prompting_notes to illustrations

Revision ID: fc05c0c3da51
Revises: 2f2f260c6eb0
Create Date: 2026-05-30 00:14:14.860827

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc05c0c3da51'
down_revision: str | Sequence[str] | None = '2f2f260c6eb0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illustrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompting_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illustrations', schema=None) as batch_op:
        batch_op.drop_column('prompting_notes')

    # ### end Alembic commands ###
