"""add access_keys + run access_key/quota_refunded

Revision ID: 450a78b8fda3
Revises: 04f7093dac00
Create Date: 2026-06-02 15:41:39.411042

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450a78b8fda3'
down_revision: str | Sequence[str] | None = '04f7093dac00'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_keys',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('runs_allowed', sa.Integer(), nullable=True),
    sa.Column('runs_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('quota_refunded', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_foreign_key(
            'fk_runs_access_key', 'access_keys', ['access_key'], ['key'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_runs_access_key', type_='foreignkey')
        batch_op.drop_column('quota_refunded')
        batch_op.drop_column('access_key')

    op.drop_table('access_keys')
    # ### end Alembic commands ###
