"""add paragraph_index to illustrations

Revision ID: a4bfd0b7ebb9
Revises: 092566a56250
Create Date: 2026-05-25 12:25:03.020737

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4bfd0b7ebb9"
down_revision: str | Sequence[str] | None = "092566a56250"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # SQLite cannot add a NOT NULL column without a default, and we want
    # the final schema to match the model (no server_default). So we add
    # the column with a temporary server_default of 0 to backfill existing
    # rows, then drop the default in a second batch step. New rows always
    # set paragraph_index explicitly via the repository.
    with op.batch_alter_table("illustrations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "paragraph_index",
                sa.Integer(),
                nullable=False,
                server_default="0",
            )
        )
    with op.batch_alter_table("illustrations", schema=None) as batch_op:
        batch_op.alter_column("paragraph_index", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("illustrations", schema=None) as batch_op:
        batch_op.drop_column("paragraph_index")

    # ### end Alembic commands ###
