"""add seed to illustration_attempt_history

Revision ID: 8ed262ed0c65
Revises: fc05c0c3da51
Create Date: 2026-05-30 19:56:09.508825

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed262ed0c65'
down_revision: str | Sequence[str] | None = 'fc05c0c3da51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illustration_attempt_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seed', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illustration_attempt_history', schema=None) as batch_op:
        batch_op.drop_column('seed')

    # ### end Alembic commands ###
