"""add scene_excerpt to illustration_attempt_history

Revision ID: 2f2f260c6eb0
Revises: f72957f6873c
Create Date: 2026-05-29 19:11:11.643480

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2f260c6eb0'
down_revision: str | Sequence[str] | None = 'f72957f6873c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illustration_attempt_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scene_excerpt', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illustration_attempt_history', schema=None) as batch_op:
        batch_op.drop_column('scene_excerpt')

    # ### end Alembic commands ###
