"""add prompting_notes to manual_illustration_sessions

Revision ID: fa7fad0a24a7
Revises: a1f6c8e21b34
Create Date: 2026-05-28 10:32:19.531663

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa7fad0a24a7"
down_revision: str | Sequence[str] | None = "a1f6c8e21b34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("manual_illustration_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prompting_notes", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("manual_illustration_sessions", schema=None) as batch_op:
        batch_op.drop_column("prompting_notes")

    # ### end Alembic commands ###
