"""add illustration_attempt_history table

Revision ID: f72957f6873c
Revises: e7b4d9c1f2a3
Create Date: 2026-05-29 15:50:56.828855

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72957f6873c'
down_revision: str | Sequence[str] | None = 'e7b4d9c1f2a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illustration_attempt_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('illustration_id', sa.String(), nullable=False),
    sa.Column('concept_attempt', sa.Integer(), nullable=False),
    sa.Column('prompt_attempt', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('concept_used', sa.Text(), nullable=False),
    sa.Column('concept_localized', sa.Text(), nullable=True),
    sa.Column('paragraph_text', sa.Text(), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('environment_label', sa.Text(), nullable=False),
    sa.Column('environment_kind', sa.String(), nullable=False),
    sa.Column('environment_aspect', sa.String(), nullable=False),
    sa.Column('contains_entity_label', sa.Text(), nullable=True),
    sa.Column('character_role', sa.String(), nullable=True),
    sa.Column('current_workflow', sa.String(), nullable=False),
    sa.Column('positive_prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=False),
    sa.Column('verdict_json', sa.Text(), nullable=False),
    sa.Column('nuance_only_failure', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['illustration_id'], ['illustrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('illustration_attempt_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_illustration_attempt_history_illustration_id'), ['illustration_id'], unique=False)
        batch_op.create_index('ix_illustration_attempt_history_illustration_nuance', ['illustration_id', 'nuance_only_failure'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illustration_attempt_history', schema=None) as batch_op:
        batch_op.drop_index('ix_illustration_attempt_history_illustration_nuance')
        batch_op.drop_index(batch_op.f('ix_illustration_attempt_history_illustration_id'))

    op.drop_table('illustration_attempt_history')
    # ### end Alembic commands ###
