"""add error_code to illustrations

Revision ID: 04f7093dac00
Revises: 7d0bc17f54f8
Create Date: 2026-06-01 12:06:01.067804

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f7093dac00'
down_revision: str | Sequence[str] | None = '7d0bc17f54f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illustrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illustrations', schema=None) as batch_op:
        batch_op.drop_column('error_code')

    # ### end Alembic commands ###
