"""add companion fields to illustrations

Revision ID: d218a2d483d6
Revises: a4bfd0b7ebb9
Create Date: 2026-05-25 14:57:25.661623

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d218a2d483d6"
down_revision: str | Sequence[str] | None = "a4bfd0b7ebb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("illustrations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("companion_description", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("companion_interaction", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("illustrations", schema=None) as batch_op:
        batch_op.drop_column("companion_interaction")
        batch_op.drop_column("companion_description")

    # ### end Alembic commands ###
