"""add i18n fields and translation tables

Revision ID: f3dec31ba972
Revises: d218a2d483d6
Create Date: 2026-05-26 11:13:35.110447

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3dec31ba972"
down_revision: str | Sequence[str] | None = "d218a2d483d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story_block_translations",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("paragraph_index", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_source_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "paragraph_index", "language"),
    )
    op.create_table(
        "story_translations",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("story_title", sa.Text(), nullable=False),
        sa.Column("story_title_source_hash", sa.String(), nullable=False),
        sa.Column("story_topic_description", sa.Text(), nullable=False),
        sa.Column("story_topic_description_source_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "language"),
    )
    op.create_table(
        "illustration_concept_translations",
        sa.Column("illustration_id", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("concept_localized", sa.Text(), nullable=False),
        sa.Column("concept_localized_source_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["illustration_id"],
            ["illustrations.id"],
        ),
        sa.PrimaryKeyConstraint("illustration_id", "language"),
    )
    with op.batch_alter_table("illustrations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("current_workflow", sa.String(), nullable=True))
        batch_op.alter_column(
            "paragraph_index",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column("character_role", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_language", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("topic_short", sa.Text(), nullable=False))
        batch_op.add_column(sa.Column("story_topic_description", sa.Text(), nullable=False))

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_language", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("detected_language", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("topic_short", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_column("topic_short")
        batch_op.drop_column("detected_language")
        batch_op.drop_column("source_language")

    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_column("story_topic_description")
        batch_op.drop_column("topic_short")
        batch_op.drop_column("source_language")

    with op.batch_alter_table("illustrations", schema=None) as batch_op:
        batch_op.alter_column("character_role", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "paragraph_index",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.drop_column("current_workflow")

    op.drop_table("illustration_concept_translations")
    op.drop_table("story_translations")
    op.drop_table("story_block_translations")
    # ### end Alembic commands ###
